authapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from authapp import views as authapp_views

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp_views.UserLoginView.as_view(), name='login'),
    path('logout', authapp_views.logout, name='logout'),
    path('register/', authapp_views.UserSignUpView.as_view(), name='register'),
    path('profile/', authapp_views.profile, name='profile'),
    path('auth/', include('mainapp.urls', )),
    path('verify/<email>/<activation_key>', authapp_views.verify, name='verify')
]

my_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp import views as mainapp_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.index, name='main'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('products/', include('mainapp.urls')),
    path('cart/', include('cartapp.urls', namespace='cart')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='orders')),

    path('', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [path('__debug__', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='order'),
    path('create/', ordersapp.OrderCreate.as_view(), name='order_create'),
    path('update/<pk>', ordersapp.OrderUpdate.as_view(), name='order_update'),
    path('delete/<pk>', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path('detail/<pk>', ordersapp.OrderDetail.as_view(), name='order_detail'),
    path('forming_complete/<pk>', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('product/<pk>/price', ordersapp.get_product_price, name='get_product_price')
]

ordersapp/models.py
from django.db import models

from django.conf import settings
from django.db import models

from cartapp.models import Cart
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCESS = 'STP'
    PROCESSED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    DONE = 'DN'
    CANCELLED = 'CNC'

    ORDER_STATUSES = (
        (FORMING,'формируется'),
        (SENT_TO_PROCESS, 'отправлен на обработку'),
        (PROCESSED, 'обработан'),
        (PAID, 'оплачен'),
        (READY, 'готов к выдаче'),
        (DONE, 'выдан'),
        (CANCELLED, 'отменён'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='создан')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='изменён')

    status = models.CharField(
        verbose_name='статус',
        choices=ORDER_STATUSES,
        max_length=4,
        default=FORMING
    )

    is_active = models.BooleanField(default=True, verbose_name='активен')

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'
        ordering = ('-created_at',)

    def get_total_quantity(self):
        _items = self.orderitems.select_related()
        _total_quantity = sum(list(map(lambda x: x.quantity , _items)))
        return _total_quantity

    def get_total_price(self):
        _items = self.orderitems.select_related()
        _total_cost = sum(list(map(lambda x: x.quantity * x.product.price, _items)))

        return _total_cost

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()




class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderitems')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    quantity = models.PositiveIntegerField(default=0, verbose_name='количество')

    def get_product_cost(self):
        return self.product.price * self.quantity

    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

ordersapp/forms.py
from django import forms

from mainapp.models import Product
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['product'].queryset = Product.get_items();

ordersapp/views.py
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import JsonResponse
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from cartapp.models import Cart
from mainapp.models import Product
from ordersapp.forms import OrderItemForm
from ordersapp.models import Order, OrderItem


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:order')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            cart_items = Cart.objects.filter(user=self.request.user)
            if cart_items.exists():
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=cart_items.count())
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = cart_items[num].product
                    form.initial['quantity'] = cart_items[num].quantity
                    form.initial['price'] = cart_items[num].product.price
            else:
                formset = OrderFormSet()

        data['orderitems'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()

            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

            if self.object.get_total_price == 0:
                self.object.delete()

            cart_items = Cart.objects.filter(user=self.request.user)
            cart_items.delete()
        return super().form_valid(form)


class OrderUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:order')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            print(orderitems.is_valid())
            if orderitems.is_valid():
                print(orderitems.is_valid())
                orderitems.instance = self.object
                orderitems.save()

            if self.object.get_total_price == 0:
                self.object.delete()

        return super().form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('orders:order')


class OrderDetail(DetailView):
    model = Order


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCESS
    order.save()

    return HttpResponseRedirect(reverse('orders:order'))


def get_product_price(request, pk):
    key = int(pk)
    if request.is_ajax():
        product_item = Product.objects.get(pk=key)
        print(product_item)
        if product_item:
            return JsonResponse({'price': product_item.price})
        return JsonResponse({'price': 0})


@receiver(pre_save, sender=Cart)
@receiver(pre_save, sender=OrderItem)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if update_fields is 'quantity' or 'products':
        if instance.pk:
            instance.product.stored_quantity -= instance.quantity - sender.get_item(instance.pk).quantity
        else:
            instance.product.stored_quantity -= instance.quantity
        instance.product.save()


@receiver(pre_delete, sender=Cart)
@receiver(pre_delete, sender=OrderItem)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.stored_quantity += instance.quantity
    instance.product.save()

ordersapp/templates/ordersapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>

    <title>GeekShop - {{ title|title }}</title>

    <link rel="icon" href="{% static 'img/pycharm-PyCharm_400x400_Twitter_logo_white.png' %}" sizes="16x16"
          type="image/png">


    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <script src="{% static 'js/auth-admin.js' %}" defer></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous" defer></script>
    <script src="{% static 'vendor/jquery/jquery.min.js' %}" crossorigin="anonymous" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            crossorigin="anonymous" defer></script>

    <script src="{% static 'js/jquery.formset.js' %}" defer></script>
    <script src="{% static 'js/ordersScripts.js' %}" defer></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </main>
    </div>
</div>

</body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
   <div class="category_delete">
       <div class="h1">Уверены, что хотите удалить?</div>
       {% include 'ordersapp/includes/inc_order_summary.html' %}
       <form action="{% url 'orders:order_delete' object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger" type="submit" value="удалить">
       </form>
       <button class="btn btn-success">
           <a href="{% url 'orders:order' %}">отмена</a>
       </button>
   </div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}

{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="cart_list">
       {% for item in object.orderitems.select_related %}
           <div class="cart_record">
               <img width="100"
                    height="100"
                    src="{{ item.product.image.url }}"
                    alt="{{ item.product.description }}">
               <span class="category_name">
                   {{ item.product.category.name }}
               </span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
               <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
               <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
           </div>
       {% endfor %}
   </div>
   {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}

{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if field.name == 'price' %}
                                    {% if field.value %}
                                        <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                            {{ field.value }}
                                        </span> руб.
                                    {% endif %}
                                {% else %}
                                    {{ field }}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="сохранить" class="btn btn-success btn-round form-control last">сохранить
            </button>
            {% include 'ordersapp/includes/inc_order_actions.html' %}
        </form>
    </div>

{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
    <div class="h2 text-center head">
        Ваши заказы,
        {% if user.first_name %}
            {{ user.first_name|title }}
        {% else %}
            Пользователь
        {% endif %}
    </div>
    <table class="table orders_list">
        <thead>
        <tr>
            <th>ID</th>
            <th>Создан</th>
            <th>Обновлен</th>
            <th>Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            {% if item.is_active %}
                <tr>
                    <td class="td1 orders_list">{{ item.pk }}</td>
                    <td>{{ item.created_at|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.updated_at|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.get_status_display }}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'orders:order_detail' item.pk %}">
                            посмотреть
                        </a>
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
                            <a class="btn btn-primary" href="{% url 'orders:order_update' item.pk %}">
                                редактировать
                            </a>
                        {% endif %}
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
                            <a class="btn btn-primary" href="{% url 'orders:order_delete' item.pk %}">
                                удалить
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-primary">
        <a class="btn btn-primary" href="{% url 'main' %}">
            на главную
        </a>
    </button>
    <button class="btn btn-primary">
        <a class="btn btn-primary" href="{% url 'orders:order_create' %}">
            новый
        </a>
    </button>

{% endblock %}